server:
  port: 8080
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

spring:
  application:
    name: authorizer
  datasource:
    url: jdbc:postgresql://${postgresql.url}/${postgresql.schema}
    username: ${postgresql.username}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250 # Tempo máximo para esperar por uma conexão do pool de conexões: 250 milliseconds
      max-lifetime: 600000 # Tempo máximo que uma conexão do pool pode ficar aberta (10 min)
      maximum-pool-size: 20 # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10
      pool-name: master
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      "[hibernate.jdbc.time_zone]": UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
