CREATE TABLE balance
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account      VARCHAR(10) NOT NULL UNIQUE,
    food_balance NUMERIC(12,2),
    meal_balance NUMERIC(12,2),
    cash_balance NUMERIC(12,2),
    version      INTEGER NOT NULL default 0,
    created_at   TIMESTAMP default current_timestamp,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_balance PRIMARY KEY (id)
);