CREATE TABLE transaction
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requested_mcc   VARCHAR(4),
    resolved_mcc    VARCHAR(4),
    merchant        VARCHAR(50),
    account         VARCHAR(10) NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    type            INTEGER NOT NULL,
    idempotency_key UUID UNIQUE NOT NULL,
    created_at      TIMESTAMP default current_timestamp,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

CREATE INDEX idx_transaction_account ON transaction (account);