CREATE TABLE balance_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account               VARCHAR(10) NOT NULL,
    transaction_id        BIGINT NOT NULL,
    previous_food_balance NUMERIC(12, 2) NOT NULL,
    previous_meal_balance NUMERIC(12, 2) NOT NULL,
    previous_cash_balance NUMERIC(12, 2) NOT NULL,
    new_food_balance      NUMERIC(12, 2) NOT NULL,
    new_meal_balance      NUMERIC(12, 2) NOT NULL,
    new_cash_balance      NUMERIC(12, 2) NOT NULL,
    created_at            TIMESTAMP,
    CONSTRAINT pk_balance_history PRIMARY KEY (id)
);

ALTER TABLE balance_history
    ADD CONSTRAINT uc_balance_history_transaction UNIQUE (transaction_id);

ALTER TABLE balance_history
    ADD CONSTRAINT FK_BALANCE_HISTORY_ON_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES transaction (id);


CREATE INDEX idx_balancy_history_account ON balance_history (account);