CREATE TABLE merchant
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_merchant_name   VARCHAR(255) NOT NULL,
    normalized_merchant_name VARCHAR(255) UNIQUE NOT NULL,
    corrected_mcc            VARCHAR(4) NOT NULL,
    created_at               TIMESTAMP NOT NULL,
    CONSTRAINT pk_merchant_mcc_mapping PRIMARY KEY (id)
);